import { getMessages } from "@/lib/i18n";

export function getAdminMemberLabels() {
  const a = getMessages().admin;
  return {
    memberNo: a.memberNo,
    memberNoHint: a.memberNoHint,
    firstName: a.firstName,
    lastName: a.lastName,
    email: a.email,
    phone: a.phone,
    password: a.password,
    status: a.status,
    statusReason: a.statusReason,
    directoryConsent: a.directoryConsent,
    collectionRef: a.duesCollectionRef,
    collectionRefHint: a.duesCollectionRefHint,
    registrationDate: a.registrationDate,
    terminationDate: a.terminationDate,
    birthDate: a.birthDate,
    preferredContact: a.preferredContact,
    addressLine1: a.addressLine1,
    addressLine2: a.addressLine2,
    postalCode: a.postalCode,
    cityName: a.cityName,
    districtName: a.districtName,
    newPassword: a.newPassword,
    newPasswordHint: a.newPasswordHint,
    legalName: a.legalName,
    tradeName: a.tradeName,
    identityNo: a.identityNo,
    taxNo: a.taxNo,
    taxOffice: a.taxOffice,
    country: a.country,
    city: a.city,
    businessPhone: a.businessPhone,
    businessEmail: a.businessEmail,
    website: a.website,
    district: a.district,
    address: a.address,
    directoryVisible: a.directoryVisible,
    verificationStatus: a.verificationStatus,
    directoryPublishTitle: a.directoryPublishTitle,
    directoryPublishReady: a.directoryPublishReady,
    directoryPublishBlocked: a.directoryPublishBlocked,
    directoryNeedActive: a.directoryNeedActive,
    directoryNeedConsent: a.directoryNeedConsent,
    directoryNeedVisible: a.directoryNeedVisible,
    directoryNeedVerified: a.directoryNeedVerified,
    sectionMembership: a.memberSectionMembership,
    sectionProfile: a.memberSectionProfile,
    sectionContact: a.memberSectionContact,
    sectionAddress: a.memberSectionAddress,
    sectionTax: a.memberSectionTax,
    sectionBusiness: a.memberSectionBusiness,
    sectionHistory: a.memberSectionHistory,
    preview: a.preview,
    save: a.save,
    delete: a.delete,
    back: a.back,
    memberStatuses: a.memberStatuses,
    verificationStatuses: a.verificationStatuses,
    fullName: a.fullName,
    businessName: a.businessName,
    registeredAt: a.registeredAt,
  };
}
